### ISSUE TITLE
Bit operator

### ISSUE THREAD

**Issue by caenguidanos** [lukeed/mrmime#4]
Hi,

In which case `(!~k)` is evaluated to `true`? [Use case](https://github.com/lukeed/mrmime/blob/915ea17ae43a10f66503650d56fc8e9da36e5dba/src/%24index.js#L6)

Thanks,

**Comment by caenguidanos** [comment]
<img width="536" alt="Captura de pantalla 2021-12-31 a las 15 51 27" src="https://user-images.githubusercontent.com/53697395/147829157-e710f3e3-0011-4297-a161-69c006d5bd47.png">

**Comment by lukeed** [comment]
It's checking for `-1`, which is perfect because it's operating on the `lastIndexOf` value, which only returns `-1` is target wasn't found.

```js
let idx = tmp.lastIndexOf('.');

let key = !~idx           // did `tmp` have "." -> extension
  ? tmp                   // no, use string as is
  : tmp.substring(++idx); // grab extension only

return mimes[key];

**Comment by caenguidanos** [comment]
Oh, ok! Thanks, Luke
